spring.application.name=project
# Server Configuration
server.port=8082
server.servlet.context-path=/api
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# ------------------------------------------------------------
# MySQL Database Configuration
# Change your datasource URL to include createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://localhost:3306/ridesharing?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


# H2 Database Connection Settings
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password

# spring.h2.console.settings.web-allow-others=true
# # H2 Console Settings (Allows you to see the DB in your browser)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# # JPA/Hibernate Settings
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update







# Logging
#logging.level.root=INFO
#logging.level.com.ridesharing=DEBUG

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Jwt Implementation
prad.security.jwt.secret=JfekXdjniEiZ9bxnIcIW3PLAAtwk2uMSmFTgnKGjVJK
prad.security.jwt.expiration-ms=86400000